### ISSUE TITLE
Необоснованное использование

### ISSUE THREAD

**Issue by neikila** [AlekseySirmais7/DzAndroid#4]
Сможешь обосновать зачем используешь
commitAllowingStateLoss
вместо commit ?

**Comment by AlekseySirmais7** [comment]
Если пользователь свернул приложение, и мы потеряли фокус, то может случится исключение. Исключение появляется тогда, когда система уже сохранила состояние, но мы  пытаемся завершить транзакцию.

**Comment by neikila** [comment]
ок
